server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: reinxx00
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: reinxx00
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: reinxx00
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: yanglemonx@163.com
    password: Yang990513@#

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yang.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.yang.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"


emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.0.104:3000/create_face_model
    checkinUrl: http://192.168.0.104:3000/checkin
  email:
    system: yanglemonx@163.com
    hr: 996881704@qq.com
  image-folder: /Users/lemonx/Documents
  code: 1111111111
  receiveNotify: http://localhost:8080/emos-wx-api/meeting/recieveNotify
workflow:
    url: http://localhost:9090/emos-workflow

wx:
  app-id: wxbb7e00261ae48601
  app-secret: 94c03494e4f45128ff43eb24ebf1ba10